server.port=8080
spring.datasource.url=${spring_datasource_url}
spring.datasource.username=${spring_datasource_username}
spring.datasource.password=${spring_datasource_password}
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

ai.service.url=${ai_service_url}
jwt.secret=${jwt_secret}
jwt.expiration=${jwt_expiration}

ai.enabled=${ai_enabled:false}

aws.region=${aws_region}