server.port=8080

spring.datasource.url=jdbc:mysql://YOUR_RDS_ENDPOINT:3306/pantrypulse

spring.datasource.username=admin

spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

ai.service.url=http://FASTAPI_SERVER:8000