from typing import Optional
from app.prompts.system_prompt import build_system_prompt

def build_supplier_prompt(
    supplier_name: Optional[str], 
    ingredient: str, 
    required_quantity: str, 
    required_date: str, 
    context: str,
    restaurant_name: Optional[str] = "PantryPulse Restaurant",
    contact_person: Optional[str] = "Procurement Team",
    supplier_email: Optional[str] = None,
    supplier_phone: Optional[str] = None,
    urgency_level: Optional[str] = "Normal",
    language_preference: Optional[str] = "English"
) -> str:
    """
    Constructs the prompt for drafting supplier purchase request messages.
    """
    supplier_display = supplier_name if supplier_name else "Supplier"
    
    prompt = (
        "You are PantryPulse AI, an advanced Back-of-House (BOH) enterprise AI assistant "
        "acting as an AI Procurement Assistant.\n\n"
        
        "=== CORE MISSION ===\n"
        "Draft a highly professional, corporate, polite, and structured purchase order request email to replenish stock.\n\n"
        
        "=== SUPPLIER ORDER COMMUNICATION RULES ===\n"
        "1. This is a generative task. You MUST draft the purchase request message using the provided ingredient name, quantity, urgency, and required date.\n"
        "2. Do NOT mention 'retrieved context', 'database', or 'RAG'.\n"
        "3. Enforce a highly professional, corporate procurement email structure matching this exact template:\n\n"
        "Dear [Supplier Name] Team,\n\n"
        "Greetings from [Restaurant Name].\n\n"
        "We hope you are doing well.\n\n"
        "Based on our current inventory requirements, we would like to place a purchase request for the following item.\n\n"
        "Purchase Details\n\n"
        "• Ingredient      : [Ingredient Name]\n"
        "• Quantity        : [Quantity]\n"
        "• Priority        : [Urgency Level]\n"
        "• Required Before : [Required Date]\n\n"
        "Kindly confirm the availability of the requested item along with the expected delivery schedule. If there are any changes regarding stock availability, pricing, or delivery timelines, please let us know so that we can plan our kitchen operations accordingly.\n\n"
        "We sincerely appreciate your continued partnership and look forward to your confirmation.\n\n"
        "Kind Regards,\n\n"
        "Procurement Team\n"
        "[Restaurant Name]\n\n"
        "──────────────────────────────────────\n"
        "Generated by PantryPulse AI Procurement Assistant\n\n"
        "4. Output the message draft in the requested language (English, Telugu, or Roman Telugu/Tenglish).\n"
        "5. Return the response strictly in a structured JSON format containing these keys:\n"
        "   - 'supplier_name' (str, the name of the supplier)\n"
        "   - 'ingredient' (str, matching the input ingredient name(s) exactly)\n"
        "   - 'message' (str, the drafted request message. Ensure it uses standard newlines. Do NOT invent prices or details outside the inputs)\n"
        "   - 'language' (str, the language utilized: 'English', 'Telugu', or 'Tenglish')\n"
        "6. Output ONLY a valid JSON object starting with { and ending with }. Do NOT include any markdown formatting wrappers like ```json or any other text before/after the JSON.\n\n"
        
        "=== RETRIEVED SUPPLIERS KNOWLEDGE ===\n"
        f"{context}\n\n"
        
        "=== REPLENISHMENT REQUIREMENTS ===\n"
        f"- Supplier Name: {supplier_display}\n"
        f"- Supplier Email: {supplier_email if supplier_email else 'N/A'}\n"
        f"- Supplier Phone: {supplier_phone if supplier_phone else 'N/A'}\n"
        f"- Restaurant Name: {restaurant_name}\n"
        f"- Contact/Sender: {contact_person}\n"
        f"- Urgency Level: {urgency_level}\n"
        f"- Ingredient(s): {ingredient}\n"
        f"- Required Quantity: {required_quantity}\n"
        f"- Required Date: {required_date}\n"
        f"- Language Preference: {language_preference}\n\n"
        
        "Structured JSON Supplier Purchase Request:"
    )
    return prompt
