from pydantic import BaseModel, Field
from typing import Any, Generic, TypeVar, List, Dict, Optional
from datetime import datetime

DataT = TypeVar('DataT')

class ApiResponse(BaseModel, Generic[DataT]):
    success: bool = Field(default=True, description="Indicates whether the request was successful")
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat() + "Z", 
        description="ISO timestamp of the response"
    )
    data: DataT = Field(..., description="Response payload")
    message: str = Field(default="Request processed successfully.", description="Status message")

# Specific Data payloads for Swagger documentation
class ChatResponseData(BaseModel):
    question: str = Field(..., description="The original user query/question")
    language: str = Field(..., description="Language detected and utilized in response (english | telugu | tenglish)")
    confidence: float = Field(default=0.95, description="Language detection confidence score (0.0 to 1.0)")
    answer: str = Field(..., description="Actionable answer text generated by the chatbot")
    sources: List[str] = Field(..., description="Categories of knowledge files accessed (e.g. recipes, safety)")
    retrieved_chunks: int = Field(..., description="Number of text chunks retrieved from vector database")
    provider: str = Field(..., description="Active LLM provider used to service this request (Gemini | OpenRouter)")
    fallback_used: bool = Field(..., description="Indicates whether secondary provider was triggered as fallback")
    response_time_ms: int = Field(..., description="Server process time for LLM routing and generation in milliseconds")

class RecipeRecommendation(BaseModel):
    recipe_id: str = Field(..., description="Unique recipe identifier")
    recipe_name: str = Field(..., description="Name of the recipe")
    description: str = Field(..., description="Short culinary description")
    matched_ingredients: List[str] = Field(..., description="Ingredients matched from user's inventory")
    missing_ingredients: List[str] = Field(..., description="Ingredients that are required but missing")
    match_percentage: int = Field(..., description="Percentage of ingredient match (0-100)")
    preparation_time_minutes: int = Field(..., description="Required preparation time in minutes")
    difficulty: str = Field(..., description="Difficulty level (Easy | Medium | Hard)")
    estimated_calories: int = Field(..., description="Estimated caloric content")
    reason_for_recommendation: str = Field(..., description="Rationale for recommendation")
    confidence: float = Field(default=0.95, description="AI recommendation confidence score (0.0 to 1.0)")

class RecipeResponseData(BaseModel):
    recipes: List[RecipeRecommendation] = Field(..., description="Recommended recipe list")

class MenuSpecial(BaseModel):
    dish: str = Field(..., description="Name of the menu dish")
    reason: str = Field(..., description="Explanation of why this dish was chosen (e.g. utilizes expiring stock)")
    matched_inventory: List[str] = Field(..., description="Ingredients matched from expiring inventory")
    missing_ingredients: List[str] = Field(default=[], description="Ingredients that are required by the recipe but missing from expiring inventory")
    estimated_profit: str = Field(..., description="Estimated profit margin or score in local currency (e.g. ₹300)")
    priority: str = Field(..., description="Priority based on inventory urgency (HIGH | MEDIUM | LOW)")
    preparation_time: int = Field(..., description="Preparation time in minutes")
    difficulty: str = Field(..., description="Difficulty level (Easy | Medium | Hard)")
    confidence: float = Field(..., description="AI confidence score (0.0 to 1.0)")

class MenuResponseData(BaseModel):
    special_menu: List[MenuSpecial] = Field(..., description="Suggested menu specials with margins, cost, and optimization reasons")

class SupplierResponseData(BaseModel):
    supplier_name: str = Field(..., description="Name of the supplier")
    ingredient: str = Field(..., description="Ingredient name to replenish")
    message: str = Field(..., description="Drafted professional email or SMS purchase request message")
    language: str = Field(..., description="Language utilized for drafting the message")
    subject: Optional[str] = Field(None, description="Drafted email subject header")
    order_id: Optional[str] = Field(None, description="Generated purchase tracking order ID")
    urgency: Optional[str] = Field(None, description="Urgency level of the request")

class HealthResponseData(BaseModel):
    status: str = Field(..., description="Overall health of FastAPI")
    rag: str = Field(..., description="Health status of RAG index and metadata files")
    faiss: str = Field(..., description="Health status of FAISS index")
    gemini: str = Field(..., description="Health status of Gemini client")
    openrouter: str = Field(..., description="Health status of OpenRouter fallback client")
    version: str = Field(..., description="KitchenSync API service version")
    providers: Optional[Dict[str, Any]] = Field(None, description="Detailed providers registry status details")
    active_provider: Optional[str] = Field(None, description="Active LLM provider serving requests")
    fallback_available: Optional[bool] = Field(None, description="Indicates if fallbacks are functional")

class DescriptionItem(BaseModel):
    dish: str = Field(..., description="Name of the dish")
    description: str = Field(..., description="Generated attractive menu description")
    tone: str = Field(..., description="Tone utilized in description")
    language: str = Field(..., description="Language utilized in description")

class DescriptionResponseData(BaseModel):
    descriptions: List[DescriptionItem] = Field(..., description="List of generated menu descriptions")

class PricingResponseData(BaseModel):
    dish: str = Field(..., description="Name of the recipe dish")
    ingredient_cost: float = Field(..., description="Ingredient cost input")
    recommended_price: int = Field(..., description="Suggested menu price in rupees")
    estimated_profit: int = Field(..., description="Estimated profit margin in rupees")
    profit_margin: int = Field(..., description="Percentage profit margin (0-100)")
    pricing_strategy: str = Field(..., description="Pricing strategy applied (Premium | Value | Standard)")
    market_position: str = Field(..., description="Market positioning (Budget | Mid-range | Upscale)")
    price_confidence: int = Field(..., description="Price recommendation confidence index (0-100)")

class RecommendedDishItem(BaseModel):
    dish: str = Field(..., description="Name of the recommended dish")
    servings: int = Field(..., ge=0, description="Suggested servings count to prepare")
    profit: int = Field(..., description="Expected profit in local currency")
    priority: str = Field(..., description="Priority based on expiry (HIGH | MEDIUM | LOW)")

class OptimizationUsageItem(BaseModel):
    ingredient: str = Field(..., description="Ingredient name")
    used_quantity: float = Field(..., ge=0.0, description="Quantity consumed")
    unit: str = Field(..., description="Unit of measurement")

class WasteSavedDetail(BaseModel):
    value: float = Field(..., ge=0.0, description="prevented waste value")
    unit: str = Field("kg", description="Unit of measurement")

class PurchaseRequirementItem(BaseModel):
    ingredient: str = Field(..., description="Ingredient name to purchase")
    required_quantity: str = Field(..., description="Estimated quantity required to replenish stock")

class OptimizationRemainingItem(BaseModel):
    ingredient: str = Field(..., description="Ingredient name")
    remaining_quantity: float = Field(..., ge=0.0, description="Quantity left after cooking")
    unit: str = Field(..., description="Unit of measurement")

class OptimizationResponseData(BaseModel):
    recommended_dishes: List[RecommendedDishItem] = Field(..., description="Optimized dish suggestions")
    inventory_usage: List[OptimizationUsageItem] = Field(..., description="Consumed ingredient details")
    estimated_revenue: int = Field(..., ge=0, description="Total expected revenue")
    currency: str = Field("INR", description="Currency unit of the revenue (e.g. INR)")
    waste_saved: WasteSavedDetail = Field(..., description="Total amount of waste saved details")
    remaining_inventory: List[OptimizationRemainingItem] = Field(..., description="Leftover inventory details")
    purchase_required: bool = Field(..., description="Whether replacement purchase is needed")
    purchase_items: List[PurchaseRequirementItem] = Field(default=[], description="Items recommended for replenishment purchase")
    reason: str = Field(..., description="Manager explanation and justification")
    language: str = Field(..., description="Detected script language")
